/// Tolerant readers for Laravel JSON.
///
/// The API is generated by PHP, where an integer column can arrive as `12`,
/// `"12"` or `12.0` depending on the driver and the cast. Parsing defensively
/// here is what stops one unexpected string from blanking a whole screen.
library;

Map<String, dynamic> asMap(Object? value) =>
    value is Map ? value.cast<String, dynamic>() : const <String, dynamic>{};

Map<String, dynamic>? asMapOrNull(Object? value) =>
    value is Map ? value.cast<String, dynamic>() : null;

List<Map<String, dynamic>> asMapList(Object? value) => value is List
    ? value.whereType<Map>().map((e) => e.cast<String, dynamic>()).toList()
    : const <Map<String, dynamic>>[];

List<T> asList<T>(Object? value, T Function(Map<String, dynamic>) parse) =>
    asMapList(value).map(parse).toList();

String asString(Object? value, [String fallback = '']) {
  if (value == null) return fallback;
  if (value is String) return value;
  return '$value';
}

String? asStringOrNull(Object? value) {
  if (value == null) return null;
  final text = value is String ? value : '$value';
  return text.isEmpty ? null : text;
}

List<String> asStringList(Object? value) =>
    value is List ? value.map((e) => '$e').where((e) => e.isNotEmpty).toList() : const <String>[];

int asInt(Object? value, [int fallback = 0]) {
  if (value is int) return value;
  if (value is num) return value.toInt();
  if (value is String) return int.tryParse(value) ?? double.tryParse(value)?.toInt() ?? fallback;
  return fallback;
}

int? asIntOrNull(Object? value) {
  if (value == null) return null;
  if (value is int) return value;
  if (value is num) return value.toInt();
  if (value is String) return int.tryParse(value) ?? double.tryParse(value)?.toInt();
  return null;
}

double asDouble(Object? value, [double fallback = 0]) {
  if (value is double) return value;
  if (value is num) return value.toDouble();
  if (value is String) return double.tryParse(value) ?? fallback;
  return fallback;
}

double? asDoubleOrNull(Object? value) {
  if (value == null) return null;
  if (value is num) return value.toDouble();
  if (value is String) return double.tryParse(value);
  return null;
}

/// Laravel writes booleans as `true`, `1` or `"1"` depending on the cast.
bool asBool(Object? value, [bool fallback = false]) {
  if (value is bool) return value;
  if (value is num) return value != 0;
  if (value is String) return value == '1' || value.toLowerCase() == 'true';
  return fallback;
}

DateTime? asDate(Object? value) {
  final text = asStringOrNull(value);
  if (text == null) return null;
  return DateTime.tryParse(text)?.toLocal();
}
